name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  api_client:
    path: packages/api_client
  auth_client:
    path: packages/auth_client
  bloc: ^8.1.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  form_inputs:
    path: packages/form_inputs
  go_router: ^13.2.0
  intl: ^0.18.1
  mocktail: ^1.0.3
  {{project_name.snakeCase()}}_ui:
    path: packages/{{project_name.snakeCase()}}_ui
  user_repository:
    path: packages/user_repository
  

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
