name: api_client
description: A client to communicate with apapa backend
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auth_client:
    path: ../auth_client
  equatable: ^2.0.5
  http: ^1.2.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  token_provider:
    path: ../token_provider

dev_dependencies:
  build_runner: ^2.4.9
  mocktail: ^1.0.0
  test: ^1.25.2
  very_good_analysis: ^5.1.0
