name: app_config_repository
description: Dart package which manages the app configuration domain.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  api_client:
    path: ../api_client
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
