name: app_config_repository
description: Dart package which manages the app configuration domain.
version: 1.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.1.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3
