name: temp
description: A Somnio App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: 3.24.3

dependencies:
  api_client:
    path: packages/api_client
  app_config_repository:
    path: packages/app_config_repository
  auth_client:
    path: packages/auth_client
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  form_inputs:
    path: packages/form_inputs
  go_router: ^14.2.9
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  temp_ui:
    path: packages/temp_ui
  url_launcher: ^6.3.0
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
