name: {{package_name.snakeCase()}}_ui
description: {{package_name.pascalCase()}} UI library
version: 0.0.1

environment: 
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.1.4

flutter:
  assets:
    - assets/

flutter_gen:
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true